# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aa3c99c6e3f6a46107fc4009cbcd4ee756a2b845d7c2ad7d223b41b5d3aedf5381bc99c6cd999d9a944debc2d6ec0b2d10dfd6362d0e582f385cbbc86e26ef8

test:
  secret_key_base: 76d3d2813e6827719ce37dec34174755e70a9477f39d466ced5e4b2b6ae44526420757a84be9330f972f64ea9f634f682992fecc65f66cfc583b101849043d63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
